customer_order_analysis:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FKJJHZA-HE36490
      user: AK9866
      password: Ak9866Chow9866@
      role: ACCOUNTADMIN
      database: DEV  # <--- Points to your Dev DB
      warehouse: COMPUTE_WH
      schema: silver
      threads: 1

    prod:
      type: snowflake
      account: FKJJHZA-HE36490
      user: AK9866
      password: Ak9866Chow9866@
      role: ACCOUNTADMIN
      database: PROD # <--- Points to your Production DB
      warehouse: COMPUTE_WH
      schema: silver
      threads: 1