customer_order_analysis:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FKJJHZA-HE36490
      user: GITHUB
      password: Ak9866Chow9866#
      role: DBT_CI_ROLE
      database: DEV  # <--- Points to your Dev DB
      warehouse: COMPUTE_WH
      schema: silver
      threads: 1


    prod:
      type: snowflake
      account: FKJJHZA-HE36490
      user: GITHUB
      password: Ak9866Chow9866#
      role:  DBT_CI_ROLE
      database: PROD # <--- Points to your Production DB
      warehouse: COMPUTE_WH
      schema: silver
      threads: 1